# Generated by Django 5.1.6 on 2025-04-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclectegory', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('modelname', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maintanance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('last_serviced_date', models.DateTimeField(auto_now_add=True)),
                ('next_serviced_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='partsordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('partid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.part')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=225)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.login')),
            ],
        ),
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshopname', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('wcontactno', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=100)),
                ('workshopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.login')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='review',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users'),
        ),
        migrations.AddField(
            model_name='maintanance',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users'),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users'),
        ),
        migrations.AddField(
            model_name='review',
            name='workshopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.workshop'),
        ),
        migrations.AddField(
            model_name='partsordering',
            name='workshopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.workshop'),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='workshopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.workshop'),
        ),
    ]
