# Generated by Django 5.1.6 on 2025-04-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0002_appoinment_login_maintanance_part_partsordering_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='location',
            new_name='Adress',
        ),
    ]
