# Generated by Django 5.1.6 on 2025-04-07 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0003_rename_location_users_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='wcontactno',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('complaint_subject', models.CharField(max_length=200)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_status', models.CharField(default='Pending', max_length=100)),
                ('complaint_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
                ('complaint_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.workshop')),
            ],
        ),
    ]
