# Generated by Django 5.1.6 on 2025-04-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0004_alter_users_contact_alter_workshop_wcontactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_replay',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
