# Generated by Django 5.1.6 on 2025-04-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0005_complaint_complaint_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('part_year', models.CharField(max_length=100)),
                ('part_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_image', models.ImageField(upload_to='parts_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='partsordering',
            name='partid',
        ),
        migrations.RemoveField(
            model_name='partsordering',
            name='workshopid',
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.CreateModel(
            name='cardpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('expirymonth', models.IntegerField()),
                ('expiryyear', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_quantity', models.IntegerField(default=1)),
                ('payment_status', models.CharField(default=0, max_length=1)),
                ('cancel_status', models.CharField(default=0, max_length=1)),
                ('refund_status', models.CharField(default=0, max_length=1)),
                ('payment_mode', models.CharField(default=0, max_length=100)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.parts')),
            ],
        ),
        migrations.DeleteModel(
            name='part',
        ),
        migrations.DeleteModel(
            name='partsordering',
        ),
    ]
