# Generated by Django 5.1.6 on 2025-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0006_parts_remove_partsordering_partid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='parts',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
