# Generated by Django 5.1.6 on 2025-04-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0007_order_order_status_alter_parts_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('cardno', models.IntegerField()),
                ('expirymonth', models.IntegerField(default=0)),
                ('expiryyear', models.IntegerField(default=0)),
                ('cvv', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.order')),
                ('refund_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
            ],
        ),
    ]
