# Generated by Django 5.1.6 on 2025-04-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0008_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cardpayment',
        ),
    ]
