# Generated by Django 5.1.6 on 2025-04-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0009_delete_cardpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('expirymonth', models.IntegerField()),
                ('expiryyear', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.order')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
            ],
        ),
    ]
