# Generated by Django 5.1.6 on 2025-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0010_cardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='url',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
