# Generated by Django 5.1.6 on 2025-04-24 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0011_appoinment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.login')),
            ],
        ),
    ]
