# Generated by Django 5.1.6 on 2025-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0012_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
