# Generated by Django 5.1.6 on 2025-05-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0013_experts_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclectegory', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('modelname', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('url', models.CharField(default=0, max_length=100)),
                ('expertid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.experts')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
            ],
        ),
    ]
