# Generated by Django 5.1.6 on 2025-05-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0015_expertslot_slotbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='url',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='ExpertAppoinment',
        ),
    ]
