# Generated by Django 5.1.6 on 2025-05-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0016_slotbooking_url_delete_expertappoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.workshop')),
            ],
        ),
    ]
