# Generated by Django 5.1.6 on 2025-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0017_workshopreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='rating',
        ),
        migrations.AddField(
            model_name='workshop',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
