# Generated by Django 5.1.6 on 2025-05-16 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0018_remove_workshop_rating_workshop_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='url',
        ),
        migrations.CreateModel(
            name='WorkshopSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.workshop')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
