# Generated by Django 5.1.6 on 2025-05-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0019_remove_appoinment_url_workshopslot_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='slot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appnew.workshopslot'),
            preserve_default=False,
        ),
    ]
