# Generated by Django 5.1.6 on 2025-05-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0021_netbanking_refundnetbanking'),
    ]

    operations = [
        migrations.AddField(
            model_name='netbanking',
            name='bankname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundnetbanking',
            name='bankname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
