# Generated by Django 5.1.6 on 2025-05-23 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0022_netbanking_bankname_refundnetbanking_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='servicechargepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.IntegerField(max_length=16, validators=[django.core.validators.RegexValidator(message='Card number must be exactly 16 digits.', regex='^\\d{16}$')])),
                ('name', models.CharField(max_length=100)),
                ('expirymonth', models.IntegerField()),
                ('expiryyear', models.IntegerField()),
                ('cvv', models.IntegerField(max_length=4, validators=[django.core.validators.RegexValidator(message='CVV must be exactly 4 digits.', regex='^\\d{4}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('appoinmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.appoinment')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.users')),
            ],
        ),
    ]
