# Generated by Django 5.1.6 on 2025-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0023_appoinment_amount_appoinment_service_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='payment_status',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
