# Generated by Django 5.1.6 on 2025-05-23 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0024_appoinment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargepayment',
            name='cardno',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Card number must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='servicechargepayment',
            name='cvv',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='CVV must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
    ]
