# Generated by Django 5.1.6 on 2025-05-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0025_alter_servicechargepayment_cardno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netbanking',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='netbanking',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='refundnetbanking',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='refundnetbanking',
            name='refund_user',
        ),
        migrations.DeleteModel(
            name='Maintanance',
        ),
        migrations.DeleteModel(
            name='netbanking',
        ),
        migrations.DeleteModel(
            name='refundnetbanking',
        ),
    ]
