# Generated by Django 5.1.6 on 2025-05-29 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0026_remove_netbanking_orderid_remove_netbanking_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='demobank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cardno', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Card number must be exactly 16 digits.', regex='^\\d{16}$')])),
                ('expirymonth', models.IntegerField()),
                ('expiryyear', models.IntegerField()),
                ('cvv', models.IntegerField(validators=[django.core.validators.RegexValidator(message='CVV must be exactly 4 digits.', regex='^\\d{4}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
