# Generated by Django 5.1.6 on 2025-05-29 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0027_demobank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demobank',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='demobank',
            name='bank_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demobank',
            name='ifsc_code',
            field=models.CharField(default=0, max_length=11, validators=[django.core.validators.RegexValidator(message='IFSC code must be 11 characters long and follow the format XXXX0XXXXXX.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
            preserve_default=False,
        ),
    ]
