# Generated by Django 5.1.6 on 2025-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0028_rename_amount_demobank_balance_demobank_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demobank',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
