# Generated by Django 5.1.6 on 2025-05-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0029_demobank_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobank',
            name='ifsc_code',
            field=models.CharField(max_length=11),
        ),
    ]
