# Generated by Django 5.1.6 on 2025-05-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0030_alter_demobank_ifsc_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cardpayment',
            new_name='payment',
        ),
    ]
