# Generated by Django 5.1.6 on 2025-06-05 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0031_rename_cardpayment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobank',
            name='cardno',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
    ]
