# Generated by Django 5.1.6 on 2025-06-07 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0032_alter_demobank_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobank',
            name='cardno',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='refund',
            name='cardno',
            field=models.CharField(max_length=100),
        ),
    ]
