# Generated by Django 5.1.6 on 2025-06-07 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0033_alter_demobank_cardno_alter_payment_cardno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargepayment',
            name='cardno',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Card number must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
    ]
