# Generated by Django 5.1.6 on 2025-06-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0034_alter_servicechargepayment_cardno'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='BRN',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
