# Generated by Django 5.2.3 on 2025-06-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0035_workshop_brn'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='experience_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='experiences_certificates/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
