# Generated by Django 5.1.6 on 2025-07-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0037_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
