from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
   path('userregister',views.userregister,name='userregister'),
   path('aboutus',views.aboutus,name='aboutus'),
   path('expertregister',views.expertregister,name='expertregister'),
   path('',views.index,name='index'),
   path('workshopregister',views.workshopregister,name='workshopregister'),
   path('userlogin',views.userlogin,name='userlogin'),
   path('adminhomepage', views.adminhomepage, name='adminhomepage'),
   path('admin_u_details', views.admin_u_details, name='admin_u_details'), 
   path('admin_w_details', views.admin_w_details, name='admin_w_details'),
   path('workshoppage',views.workshoppage,name='workshoppage'),
   path('expertpage',views.expertpage,name='expertpage'),
   path('userpage',views.userpage,name='userpage'),
   path('logout',views.logout_view,name='logout'),
   path('editworkshop',views.editworkshop,name='editworkshop'),
   path('editexpert',views.editexpert,name='editexpert'),
   path('edituser/',views.edituser,name='edituser'),
   path('workshopdetailpage',views.workshopdetailpage,name='workshopdetailpage'),
   path('appointment/<int:slot_id>/<int:workshopid>/', views.appointment, name='appointment'),
   path('viewappoinment',views.viewappoinment,name='viewappoinment'),
   path('edit_appoinment/<int:complaint_id>/', views.edit_appoinment, name='edit_appoinment'),
   path('delete_appoinment/<int:complaint_id>/', views.delete_appoinment, name='delete_appoinment'),
   path('workshopappoinmentview',views.workshopappoinmentview,name='workshopappoinmentview'),
   path('addprogress/<int:complaint_id>/', views.addprogress, name='addprogress'),
   path('complaintadding/<int:id>/', views.complaintadding, name='complaintadding'),
   path('complaintview/', views.complaintview, name='complaintview'),
   path('workcomplaint',views.workcomplaint,name='workcomplaint'),
   path('delete_complaint/<int:id>/', views.delete_complaint, name='delete_complaint'),
   path('edit_complaint/<int:complaint_id>/', views.edit_complaint, name='edit_complaint'),
   path('adminreplaycomplaint/<int:complaint_id>/', views.adminreplaycomplaint, name='adminreplaycomplaint'),
   path('accepted/<int:id>/', views.accepted, name='accepted'),
   path('rejected/<int:id>/', views.rejected, name='rejected'),
   path('acceptedexpert/<int:id>/', views.acceptedexpert, name='acceptedexpert'),
   path('rejectedexpert/<int:id>/', views.rejectedexpert, name='rejectedexpert'),
   path('rejecteduser/<int:id>/', views.rejecteduser, name='rejecteduser'),
   path('accepteduser/<int:id>/', views.accepteduser, name='accepteduser'),
   path('partsadd',views.partsadd,name='partsadd'),
   path('partlist',views.partlist,name='partlist'),
   path('delete_part/<int:id>/', views.delete_part, name='delete_part'),
   path('edit_part/<int:id>/', views.edit_part, name='edit_part'),
   path('partsview',views.partsview,name='partsview'),
   path('orderforparts/<int:partid>/',views.orderforparts,name='orderforparts'),
   path('cartdetails',views.cartdetails,name='cartdetails'),
   path('deletecart/<int:id>/', views.deletecart, name='deletecart'),
   path('partsorder',views.partsorder,name='partsorder'),
   path('quantity_selection/<int:partid>/', views.quantity_selection, name='quantity_selection'),
   path('buying/<int:partid>', views.buying, name='buying'),
   path('payment_process/<int:partid>/', views.payment_process, name='payment_process'),
   path('cancelpaymentprocess/<int:partid>/',views.cancelpaymentprocess,name='cancelpaymentprocess'),
   path('orderdetails',views.orderdetails,name='orderdetails'),
   path('cancelproduct/<int:id>/', views.cancelproduct, name='cancelproduct'),
   path('canceldetails',views.canceldetails,name='canceldetails'),
   path('refundpayment/<int:id>/',views.refundpayment,name='refundpayment'),
   path('refund_receipt/<int:orderid>/', views.refund_receipt, name='refund_receipt'),
   path('refund_receiptuser/<int:orderid>/', views.refund_receiptuser, name='refund_receiptuser'),
   path('refundlist',views.refundlist,name='refundlist'),
   path('payment_receipt/<int:orderid>/', views.payment_receipt, name='payment_receipt'),
   path('payment_receiptuser/<int:orderid>/', views.payment_receiptuser, name='payment_receiptuser'),
   path('video_call/<int:video_call_id>/', views.videocall, name='video_call'),
   path('admin_e_details',views.admin_e_details,name="admin_e_details"),
   path('expertdetails',views.expertdetails,name="expertdetails"),
   path('save-appointment-url/<int:pk>/', views.save_appointment_url, name='save-appointment-url'), 
   path('signup/', views.signup, name='signup'),
   path('update_service/<int:issue_id>/', views.update_service, name='update_service'),
   path('add-service-charge/<int:id>/', views.add_service_charge, name='add_service_charge'),
   
   path('update_service',views.update_service,name='update_service'),
   path('add_slot/', views.add_expert_slot, name='add_expert_slot'),
   path('view_slots/', views.view_expert_slots, name='view_expert_slots'),
   path('delete_slot/<int:slot_id>/', views.delete_expert_slot, name='delete_expert_slot'),
   path('view_bookings/', views.view_slot_bookings, name='view_slot_bookings'),
   path('slots/', views.available_slots, name='available_slots'),
   path('book_slot/<int:slot_id>/', views.book_slot, name='book_slot'),
   path('my_booked_slots/', views.my_booked_slots, name='my_booked_slots'),
   path('cancel_slot_booking/<int:booking_id>/', views.cancel_slot_booking, name='cancel_slot_booking'),
   path('viewexpertslot/<int:id>/',views.viewexpertslot,name='viewexpertslot'),
   path('add_workshop_review/<int:workshop_id>/', views.add_workshop_review, name='add_workshop_review'),
   path('workshopreview/<int:workshop_id>/', views.workshopreview, name='workshopreview'),
   path('viewreview', views.viewreview, name='viewreview'),
   path('view_all_workshops/', views.view_all_workshops, name='view_all_workshops'),
   path('w_review/<int:workshop_id>/', views.w_review, name='w_review'),
   path('view_all_experts/', views.view_all_experts, name='view_all_experts'),
   path('view_all_parts/', views.view_all_parts, name='view_all_parts'),
   path('add_workshop_slot/', views.add_workshop_slot, name='add_workshop_slot'),
   path('view_workshop_slots', views.view_workshop_slots, name='view_workshop_slots'),
   path('delete_workshop_slot/<int:slot_id>/', views.delete_workshop_slot, name='delete_workshop_slot'),
   path('workshop_slots/<int:workshop_id>/', views.workshop_slots, name='workshop_slots'),
   path('all_workshops_with_slots/', views.all_workshops_with_slots, name='all_workshops_with_slots'),
   path('edit_expertslot/<int:expertslot_id>/', views.edit_expertslot, name='edit_expertslot'),
   path('servicecharge/<int:id>/', views.servicecharge, name='servicecharge'),
   path('service_charge_receipt/<int:ap_id>/', views.service_charge_receipt, name='service_charge_receipt'),
   path('service_charge_receiptworkshop/<int:ap_id>/', views.service_charge_receiptworkshop, name='service_charge_receiptworkshop'),
   path('user_dashboard',views.user_dashboard,name='user_dashboard'),
   path('todays_expert_bookings', views.todays_expert_bookings, name='todays_expert_bookings'),
   path('todays_workshop_bookings', views.todays_workshop_bookings, name='todays_workshop_bookings'),
   path('adddemoaccount', views.adddemoaccount, name='adddemoaccount'),
   path('viewdemobank', views.viewdemobank, name='viewdemobank'),
   path('demobank/add_amount/<int:account_id>/', views.add_amount_demobank, name='add_amount_demobank'),
   path('demobank/delete/<int:account_id>/', views.delete_demobank, name='delete_demobank'),
   path('admin_reply_complaint/<int:complaint_id>/', views.admin_reply_complaint, name='admin_reply_complaint'),
   path('partsorderhistory', views.partsorderhistory, name='partsorderhistory'), 
   path('adminregister', views.adminregister, name='adminregister'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/', views.reset_password, name='reset_password'),
           path('vehicle-diagnosis/', views.vehicle_diagnosis_view, name='vehicle_diagnosis'),

    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)